#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== Keycloak Setup for MongoDB & Redis Web UIs ===${NC}"
echo ""
echo -e "${YELLOW}This script will guide you through creating Keycloak clients${NC}"
echo -e "${YELLOW}for Mongo Express and Redis Commander.${NC}"
echo ""
echo -e "${BLUE}Prerequisites:${NC}"
echo "1. Keycloak must be running at https://keycloak.ai-servicers.com"
echo "2. You need admin access to Keycloak"
echo ""
echo -e "${YELLOW}Please create the following clients in Keycloak:${NC}"
echo ""
echo "=================================="
echo "Client 1: Mongo Express"
echo "=================================="
echo "  Client ID: mongo-express"
echo "  Client Type: OpenID Connect"
echo "  Client Protocol: openid-connect"
echo "  Access Type: Confidential"
echo "  Valid Redirect URIs: https://mongo.ai-servicers.com/*"
echo "  Web Origins: https://mongo.ai-servicers.com"
echo ""
echo "After creation, go to Credentials tab and copy the Secret"
echo ""
echo "=================================="
echo "Client 2: Redis Commander"
echo "=================================="
echo "  Client ID: redis-commander"
echo "  Client Type: OpenID Connect"
echo "  Client Protocol: openid-connect"
echo "  Access Type: Confidential"
echo "  Valid Redirect URIs: https://redis.ai-servicers.com/*"
echo "  Web Origins: https://redis.ai-servicers.com"
echo ""
echo "After creation, go to Credentials tab and copy the Secret"
echo ""
echo "=================================="
echo "Group Restriction (Optional)"
echo "=================================="
echo "To restrict access to administrators group only:"
echo "1. Go to each client -> Client scopes -> [client]-dedicated"
echo "2. Add mapper -> By configuration -> Group Membership"
echo "3. Configure:"
echo "   - Name: groups"
echo "   - Token Claim Name: groups"
echo "   - Full group path: ON"
echo "   - Add to ID token: ON"
echo "   - Add to access token: ON"
echo "   - Add to userinfo: ON"
echo ""
echo -e "${YELLOW}Once you have the client secrets, update the environment files:${NC}"
echo "  $HOME/projects/secrets/mongo-express.env"
echo "  $HOME/projects/secrets/redis-commander.env"
echo ""
echo -e "${GREEN}Then run the deployment scripts:${NC}"
echo "  /home/administrator/projects/mongodb/deploy-mongo-express.sh"
echo "  /home/administrator/projects/redis/deploy-redis-commander.sh"